apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: dingo
spec:
    version: 7.6.2
    http:
        service:
            spec:
                type: LoadBalancer
    secureSettings:
    - secretName: gcs-credentials
    nodeSets:
    - name: zone-a-master
      count: 1
      config:
          node.master: true
          node.data: true
          node.ingest: true
          xpack.ml.enabled: false
          node.store.allow_mmap: true
          index.store.type: hybridfs
          node.attr.zone: asia-east1-a
          cluster.routing.allocation.awareness.attributes: zone
          cluster.remote.connect: true
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
            accessModes:
            - ReadWriteOnce
            resources:
                requests:
                    storage: 10Gi
            storageClassName: dingo-pdssd
      updateStrategy:
          changeBudget:
              maxSurge: 3
              maxUnavailable: 1
      podDisruptionBudget:
          spec:
              minAvailable: 1
              selector:
                  matchLables:
                      elasticsearch.k8s.elastic.co/cluster-name: dingo
      podTemplate:
          spec:
              containers:
              - name: elasticsearch
                resources:
                    requests:
                        memory: 8Gi
                        cpu: 1
                    limits:
                        memory: 8Gi
                        cpu: 2
                env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
                - name: PRE_STOP_MAX_WAIT_SECONDS
                  value: "20"
                - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
                  value: "30"
                - name: READINESS_PROBE_TIMEOUT
                  value: "10"
                readinessProbe:
                    exec:
                        command:
                        - bash
                        - -c
                        - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                    failureThreshold: 3
                    initialDelaySeconds: 10
                    periodSeconds: 12
                    successThreshold: 1
                    timeoutSeconds: 12
              initContainers:
              #- name: sysctl
                 #securityContext:
                     #priviledged: true
                #command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
              - name: install-plugins
                command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install --batch repository-gcs
              affinity:
                  podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                            labelSelector:
                                matchLabels:
                                    elasticsearch.k8s.elastic.co/cluster-name: dingo
                            topologyKey: kubernetes.io/hostname
                  nodeAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                          nodeSelectorTerms:
                          - matchExpressions:
                              # - key: topology.kubernetes.io/zone # v1.18+
                              - key: failure-domain.beta.kubernetes.io/zone
                                operator: In
                                values:
                                - asia-east1-a
