apiVersion: v1
kind: Pod
metadata:
  name: command-demo-neverRestart
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "echo hello cmd1; exit 1"]
  restartPolicy: Never
